/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Semester;

import Home.Gpa;
import java.awt.event.MouseListener;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author User
 */
public class Sem7 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sem7
     */
    public Sem7() {
        initComponents();
        
        BasicInternalFrameUI bb=((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI());
        for(MouseListener listener:bb.getNorthPane().getMouseListeners()){
            bb.getNorthPane().removeMouseListener(listener);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g8 = new javax.swing.JComboBox<>();
        g3 = new javax.swing.JComboBox<>();
        g1 = new javax.swing.JComboBox<>();
        btn1 = new javax.swing.JButton();
        g7 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        g6 = new javax.swing.JComboBox<>();
        g4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        g2 = new javax.swing.JComboBox<>();
        g5 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        s1gpa = new javax.swing.JLabel();
        com1 = new javax.swing.JComboBox<>();
        com2 = new javax.swing.JComboBox<>();
        com4 = new javax.swing.JComboBox<>();
        com3 = new javax.swing.JComboBox<>();
        com5 = new javax.swing.JComboBox<>();
        com6 = new javax.swing.JComboBox<>();
        com7 = new javax.swing.JComboBox<>();
        com8 = new javax.swing.JComboBox<>();
        com9 = new javax.swing.JComboBox<>();
        com10 = new javax.swing.JComboBox<>();
        g9 = new javax.swing.JComboBox<>();
        g10 = new javax.swing.JComboBox<>();
        g11 = new javax.swing.JComboBox<>();
        g12 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Semester 7");
        setPreferredSize(new java.awt.Dimension(1088, 574));

        g8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g8ActionPerformed(evt);
            }
        });

        g3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g3ActionPerformed(evt);
            }
        });

        g1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(102, 102, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn1.setText("Calculate Semester GPA");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        g7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g7ActionPerformed(evt);
            }
        });

        jLabel2.setText("CST496-2  Entrepreneurship");

        g6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g6ActionPerformed(evt);
            }
        });

        g4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g4ActionPerformed(evt);
            }
        });

        jLabel1.setText("CST447-2  Mobile Application Development");

        g2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });

        g5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g5ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel17.setText("7 Semester GPA:");

        s1gpa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        com1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 2 optional subject", "CST474-2  Bioinformatics", "CST446-2  Enterprise Resource Planning(ERP)", "CST478-2  Robotics", "CST475-2  Data Warehousing and Data Mining", "CST453-2  Cloud Computing", "CST473-2  Augmented Reality", "CST449-2  UI and UX Engineering", "CST476-2  Digital Forensics", "CST464-2  Embedded Systems and Device Interfacing", "CST448-2  Software Design Patterns", "CST452-2  Middleware Architecture", "CST435-2  Computer Networks-III" }));

        com2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 2 optional subject", "CST474-2  Bioinformatics", "CST446-2  Enterprise Resource Planning(ERP)", "CST478-2  Robotics", "CST475-2  Data Warehousing and Data Mining", "CST453-2  Cloud Computing", "CST473-2  Augmented Reality", "CST449-2  UI and UX Engineering", "CST476-2  Digital Forensics", "CST464-2  Embedded Systems and Device Interfacing", "CST448-2  Software Design Patterns", "CST452-2  Middleware Architecture", "CST435-2  Computer Networks-III" }));

        com4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 2 optional subject", "CST474-2  Bioinformatics", "CST446-2  Enterprise Resource Planning(ERP)", "CST478-2  Robotics", "CST475-2  Data Warehousing and Data Mining", "CST453-2  Cloud Computing", "CST473-2  Augmented Reality", "CST449-2  UI and UX Engineering", "CST476-2  Digital Forensics", "CST464-2  Embedded Systems and Device Interfacing", "CST448-2  Software Design Patterns", "CST452-2  Middleware Architecture", "CST435-2  Computer Networks-III" }));

        com3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 2 optional subject", "CST474-2  Bioinformatics", "CST446-2  Enterprise Resource Planning(ERP)", "CST478-2  Robotics", "CST475-2  Data Warehousing and Data Mining", "CST453-2  Cloud Computing", "CST473-2  Augmented Reality", "CST449-2  UI and UX Engineering", "CST476-2  Digital Forensics", "CST464-2  Embedded Systems and Device Interfacing", "CST448-2  Software Design Patterns", "CST452-2  Middleware Architecture", "CST435-2  Computer Networks-III" }));

        com5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 2 optional subject", "CST474-2  Bioinformatics", "CST446-2  Enterprise Resource Planning(ERP)", "CST478-2  Robotics", "CST475-2  Data Warehousing and Data Mining", "CST453-2  Cloud Computing", "CST473-2  Augmented Reality", "CST449-2  UI and UX Engineering", "CST476-2  Digital Forensics", "CST464-2  Embedded Systems and Device Interfacing", "CST448-2  Software Design Patterns", "CST452-2  Middleware Architecture", "CST435-2  Computer Networks-III" }));

        com6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 2 optional subject", "CST474-2  Bioinformatics", "CST446-2  Enterprise Resource Planning(ERP)", "CST478-2  Robotics", "CST475-2  Data Warehousing and Data Mining", "CST453-2  Cloud Computing", "CST473-2  Augmented Reality", "CST449-2  UI and UX Engineering", "CST476-2  Digital Forensics", "CST464-2  Embedded Systems and Device Interfacing", "CST448-2  Software Design Patterns", "CST452-2  Middleware Architecture", "CST435-2  Computer Networks-III" }));

        com7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 3 optional subject", "CST483-3  Remote Sensing and Image Interpretation", "CST477-3  Fuzzy Logic and Neural Networks", "CST436-3  System Administration and Maintenance", "IIT449-3  GIS for Business" }));

        com8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 3 optional subject", "CST483-3  Remote Sensing and Image Interpretation", "CST477-3  Fuzzy Logic and Neural Networks", "CST436-3  System Administration and Maintenance", "IIT449-3  GIS for Business" }));

        com9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 3 optional subject", "CST483-3  Remote Sensing and Image Interpretation", "CST477-3  Fuzzy Logic and Neural Networks", "CST436-3  System Administration and Maintenance", "IIT449-3  GIS for Business" }));

        com10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Credit 3 optional subject", "CST483-3  Remote Sensing and Image Interpretation", "CST477-3  Fuzzy Logic and Neural Networks", "CST436-3  System Administration and Maintenance", "IIT449-3  GIS for Business" }));

        g9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g9ActionPerformed(evt);
            }
        });

        g10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g10ActionPerformed(evt);
            }
        });

        g11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g11ActionPerformed(evt);
            }
        });

        g12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "E" }));
        g12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g12ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("3 Credit Optional Subjects:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("2 Credit Optional Subjects:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("You must select\n12 optional credits\n");
        jScrollPane1.setViewportView(jTextArea1);

        btn3.setBackground(new java.awt.Color(102, 102, 255));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn3.setText("Save as xls file");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(com1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com5, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com6, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(s1gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(com7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com8, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com9, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com10, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(g9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(s1gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(com7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(com8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(com9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(com10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2438, 2438, 2438))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void g8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g8ActionPerformed

    private void g3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g3ActionPerformed

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String grade1=(String)g1.getSelectedItem();
        String grade2=(String)g2.getSelectedItem();
        String grade3=(String)g3.getSelectedItem();
        String grade4=(String)g4.getSelectedItem();
        String grade5=(String)g5.getSelectedItem();
        String grade6=(String)g6.getSelectedItem();
        String grade7=(String)g7.getSelectedItem();
        String grade8=(String)g8.getSelectedItem();
        String grade9=(String)g9.getSelectedItem();
        String grade10=(String)g10.getSelectedItem();
        String grade11=(String)g11.getSelectedItem();
        String grade12=(String)g12.getSelectedItem();

        double gpv1=0,gpv2=0,gpv3=0,gpv4=0,gpv5=0,gpv6=0,gpv7=0,gpv8=0,gpv9=0,gpv10=0,gpv11=0,gpv12=0,res=0;

        switch(grade1){
            case "A+":
            gpv1=4.00*2;
            break;
            case "A":
            gpv1=4.00*2;
            break;
            case "A-":
            gpv1=3.70*2;
            break;
            case "B+":
            gpv1=3.30*2;
            break;
            case "B":
            gpv1=3.00*2;
            break;
            case "B-":
            gpv1=2.70*2;
            break;
            case "C+":
            gpv1=2.30*2;
            break;
            case "C":
            gpv1=2.00*2;
            break;
            case "C-":
            gpv1=1.70*2;
            break;
            case "D+":
            gpv1=1.30*2;
            break;
            case "D":
            gpv1=1.00*2;
            break;
            case "E":
            gpv1=0;
            break;
            default :
            gpv1=0;
        }

        switch(grade2){
            case "A+":
            gpv2=4.00*2;
            break;
            case "A":
            gpv2=4.00*2;
            break;
            case "A-":
            gpv2=3.70*2;
            break;
            case "B+":
            gpv2=3.30*2;
            break;
            case "B":
            gpv2=3.00*2;
            break;
            case "B-":
            gpv2=2.70*2;
            break;
            case "C+":
            gpv2=2.30*2;
            break;
            case "C":
            gpv2=2.00*2;
            break;
            case "C-":
            gpv2=1.70*2;
            break;
            case "D+":
            gpv2=1.30*2;
            break;
            case "D":
            gpv2=1.00*2;
            break;
            case "E":
            gpv2=0;
            break;
            default :
            gpv2=0;
        }

        switch(grade3){
            case "A+":
            gpv3=4.00*2;
            break;
            case "A":
            gpv3=4.00*2;
            break;
            case "A-":
            gpv3=3.70*2;
            break;
            case "B+":
            gpv3=3.30*2;
            break;
            case "B":
            gpv3=3.00*2;
            break;
            case "B-":
            gpv3=2.70*2;
            break;
            case "C+":
            gpv3=2.30*2;
            break;
            case "C":
            gpv3=2.00*2;
            break;
            case "C-":
            gpv3=1.70*2;
            break;
            case "D+":
            gpv3=1.30*2;
            break;
            case "D":
            gpv3=1.00*2;
            break;
            case "E":
            gpv3=0;
            break;
            default :
            gpv3=0;
        }

        switch(grade4){
            case "A+":
            gpv4=4.00*2;
            break;
            case "A":
            gpv4=4.00*2;
            break;
            case "A-":
            gpv4=3.70*2;
            break;
            case "B+":
            gpv4=3.30*2;
            break;
            case "B":
            gpv4=3.00*2;
            break;
            case "B-":
            gpv4=2.70*2;
            break;
            case "C+":
            gpv4=2.30*2;
            break;
            case "C":
            gpv4=2.00*2;
            break;
            case "C-":
            gpv4=1.70*2;
            break;
            case "D+":
            gpv4=1.30*2;
            break;
            case "D":
            gpv4=1.00*2;
            break;
            case "E":
            gpv4=0;
            break;
            default :
            gpv4=0;
        }

        switch(grade5){
            case "A+":
            gpv5=4.00*2;
            break;
            case "A":
            gpv5=4.00*2;
            break;
            case "A-":
            gpv5=3.70*2;
            break;
            case "B+":
            gpv5=3.30*2;
            break;
            case "B":
            gpv5=3.00*2;
            break;
            case "B-":
            gpv5=2.70*2;
            break;
            case "C+":
            gpv5=2.30*2;
            break;
            case "C":
            gpv5=2.00*2;
            break;
            case "C-":
            gpv5=1.70*2;
            break;
            case "D+":
            gpv5=1.30*2;
            break;
            case "D":
            gpv5=1.00*2;
            break;
            case "E":
            gpv5=0;
            break;
            default :
            gpv5=0;
        }

        switch(grade6){
            case "A+":
            gpv6=4.00*2;
            break;
            case "A":
            gpv6=4.00*2;
            break;
            case "A-":
            gpv6=3.70*2;
            break;
            case "B+":
            gpv6=3.30*2;
            break;
            case "B":
            gpv6=3.00*2;
            break;
            case "B-":
            gpv6=2.70*2;
            break;
            case "C+":
            gpv6=2.30*2;
            break;
            case "C":
            gpv6=2.00*2;
            break;
            case "C-":
            gpv6=1.70*2;
            break;
            case "D+":
            gpv6=1.30*2;
            break;
            case "D":
            gpv6=1.00*2;
            break;
            case "E":
            gpv6=0;
            break;
            default :
            gpv6=0;
        }

        switch(grade7){
            case "A+":
            gpv7=4.00*2;
            break;
            case "A":
            gpv7=4.00*2;
            break;
            case "A-":
            gpv7=3.70*2;
            break;
            case "B+":
            gpv7=3.30*2;
            break;
            case "B":
            gpv7=3.00*2;
            break;
            case "B-":
            gpv7=2.70*2;
            break;
            case "C+":
            gpv7=2.30*2;
            break;
            case "C":
            gpv7=2.00*2;
            break;
            case "C-":
            gpv7=1.70*2;
            break;
            case "D+":
            gpv7=1.30*2;
            break;
            case "D":
            gpv7=1.00*2;
            break;
            case "E":
            gpv7=0;
            break;
            default :
            gpv7=0;
        }

        switch(grade8){
            case "A+":
            gpv8=4.00*2;
            break;
            case "A":
            gpv8=4.00*2;
            break;
            case "A-":
            gpv8=3.70*2;
            break;
            case "B+":
            gpv8=3.30*2;
            break;
            case "B":
            gpv8=3.00*2;
            break;
            case "B-":
            gpv8=2.70*2;
            break;
            case "C+":
            gpv8=2.30*2;
            break;
            case "C":
            gpv8=2.00*2;
            break;
            case "C-":
            gpv8=1.70*2;
            break;
            case "D+":
            gpv8=1.30*2;
            break;
            case "D":
            gpv8=1.00*2;
            break;
            case "E":
            gpv8=0;
            break;
            default :
            gpv8=0;
        }
        
        switch(grade9){
            case "A+":
            gpv9=4.00*3;
            break;
            case "A":
            gpv9=4.00*3;
            break;
            case "A-":
            gpv9=3.70*3;
            break;
            case "B+":
            gpv9=3.30*3;
            break;
            case "B":
            gpv9=3.00*3;
            break;
            case "B-":
            gpv9=2.70*3;
            break;
            case "C+":
            gpv9=2.30*3;
            break;
            case "C":
            gpv9=2.00*3;
            break;
            case "C-":
            gpv9=1.70*3;
            break;
            case "D+":
            gpv9=1.30*3;
            break;
            case "D":
            gpv9=1.00*3;
            break;
            case "E":
            gpv9=0;
            break;
            default :
            gpv9=0;
        }
        
        switch(grade10){
            case "A+":
            gpv10=4.00*3;
            break;
            case "A":
            gpv10=4.00*3;
            break;
            case "A-":
            gpv10=3.70*3;
            break;
            case "B+":
            gpv10=3.30*3;
            break;
            case "B":
            gpv10=3.00*3;
            break;
            case "B-":
            gpv10=2.70*3;
            break;
            case "C+":
            gpv10=2.30*3;
            break;
            case "C":
            gpv10=2.00*3;
            break;
            case "C-":
            gpv10=1.70*3;
            break;
            case "D+":
            gpv10=1.30*3;
            break;
            case "D":
            gpv10=1.00*3;
            break;
            case "E":
            gpv10=0;
            break;
            default :
            gpv10=0;
        }
        
        switch(grade11){
            case "A+":
            gpv11=4.00*3;
            break;
            case "A":
            gpv11=4.00*3;
            break;
            case "A-":
            gpv11=3.70*3;
            break;
            case "B+":
            gpv11=3.30*3;
            break;
            case "B":
            gpv11=3.00*3;
            break;
            case "B-":
            gpv11=2.70*3;
            break;
            case "C+":
            gpv11=2.30*3;
            break;
            case "C":
            gpv11=2.00*3;
            break;
            case "C-":
            gpv11=1.70*3;
            break;
            case "D+":
            gpv11=1.30*3;
            break;
            case "D":
            gpv11=1.00*3;
            break;
            case "E":
            gpv11=0;
            break;
            default :
            gpv11=0;
        }
        
        switch(grade12){
            case "A+":
            gpv12=4.00*3;
            break;
            case "A":
            gpv12=4.00*3;
            break;
            case "A-":
            gpv12=3.70*3;
            break;
            case "B+":
            gpv12=3.30*3;
            break;
            case "B":
            gpv12=3.00*3;
            break;
            case "B-":
            gpv12=2.70*3;
            break;
            case "C+":
            gpv12=2.30*3;
            break;
            case "C":
            gpv12=2.00*3;
            break;
            case "C-":
            gpv12=1.70*3;
            break;
            case "D+":
            gpv12=1.30*3;
            break;
            case "D":
            gpv12=1.00*3;
            break;
            case "E":
            gpv12=0;
            break;
            default :
            gpv12=0;
        }
        String[] s=new String[10];
        String[] g=new String[11];
        s[0]=(String)com1.getSelectedItem();
        s[1] =(String)com2.getSelectedItem();
        s[2]=(String)com3.getSelectedItem();
        s[3]=(String)com4.getSelectedItem();
        s[4]=(String)com5.getSelectedItem();
        s[5]=(String)com6.getSelectedItem();
        s[6]=(String)com7.getSelectedItem();
        s[7]=(String)com8.getSelectedItem();
        s[8]=(String)com9.getSelectedItem();
        s[9]=(String)com10.getSelectedItem();
        
        g[0]=grade3;
        g[1]=grade4;
        g[2]=grade5;
        g[3]=grade6;
        g[4]=grade7;
        g[5]=grade8;
        g[6]=grade9;
        g[7]=grade10;
        g[8]=grade11;
        g[9]=grade12;
        
        int count=0;
        int check=0;
        for(int i=0;i<6;i++){
            if((!(s[i].equals("Select Credit 2 optional subject")))){
                count=count+2;
                
                 for(int j=i+1;j<6;j++){
                        if((!(s[i].equals("Select Credit 2 optional subject"))) && (s[i].equals(s[j]))){
                        check=1;
            }
            }                                 
            }
            
            if((s[i].equals("Select Credit 2 optional subject"))&& (!(g[i].equals("Grade")))){
                        check=1;
                    }
            
           
        }
        
        for(int i=6;i<10;i++){
                if((!(s[i].equals("Select Credit 3 optional subject")))){
                count=count+3;
                
                 if(i<9){
                    for(int j=i+1;j<10;j++){
                        if((!(s[i].equals("Select Credit 2 optional subject"))) && (s[i].equals(s[j]))){
                        check=1;
                }
                }
            }
                 
 
                
            }
                if((s[i].equals("Select Credit 3 optional subject"))&& (!(g[i].equals("Grade")))){
                        check=1;
                    }
            
           
        }
        

        if(count==12 && check==0){
            
            res=(gpv1+gpv2+gpv3+gpv4+gpv5+gpv6+gpv7+gpv8+gpv9+gpv10+gpv11+gpv12)/16;
            res=Math.round(res*100.0)/100.0;                   
            s1gpa.setText(Double.toString(res));
            
        }
        
        else{
            JOptionPane.showMessageDialog(this,"Plese check whether Optional subjects you entered correctly!");
        }
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void g7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g7ActionPerformed

    private void g6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g6ActionPerformed

    private void g4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g4ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g2ActionPerformed

    private void g5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g5ActionPerformed

    private void g9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g9ActionPerformed

    private void g10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g10ActionPerformed

    private void g11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g11ActionPerformed

    private void g12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g12ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        Workbook workbook = new HSSFWorkbook();
        Sheet sheet1=workbook.createSheet("Sem7 Gpa");
        //Sheet sheet2=workbook.createSheet("calculate");
        sheet1.setColumnWidth(0,15000);
        
        Row row0=sheet1.createRow(0);
        Cell cell0=row0.createCell(0);
        cell0.setCellValue("Subjects");
        
        
        Row row1=sheet1.createRow(2);
        Cell cell1=row1.createCell(0);
        cell1.setCellValue("CST447-2  Mobile Application Development");
        Cell cellA1=row1.createCell(1);
        cellA1.setCellValue((g1.getSelectedItem()).toString());
        
      
        
        
        Row row2=sheet1.createRow(3);
        Cell cell2=row2.createCell(0);
        cell2.setCellValue("CST496-2  Entrepreneurship");
        Cell cellA2=row2.createCell(1);
        cellA2.setCellValue((g2.getSelectedItem()).toString());
        
        
        
        Row row3=sheet1.createRow(4);
        Cell cell3=row3.createCell(0);
        cell3.setCellValue(com1.getSelectedItem().toString());
        Cell cellA3=row3.createCell(1);
        cellA3.setCellValue((g3.getSelectedItem()).toString());
        
         Row row4=sheet1.createRow(5);
        Cell cell4=row4.createCell(0);
        cell4.setCellValue(com2.getSelectedItem().toString());
        Cell cellA4=row4.createCell(1);
        cellA4.setCellValue((g4.getSelectedItem()).toString());
        
        Row row5=sheet1.createRow(6);
        Cell cell5=row5.createCell(0);
        cell5.setCellValue(com3.getSelectedItem().toString());
        Cell cellA5=row5.createCell(1);
        cellA5.setCellValue((g5.getSelectedItem()).toString());
        
        Row row6=sheet1.createRow(7);
        Cell cell6=row6.createCell(0);
        cell6.setCellValue(com4.getSelectedItem().toString());
        Cell cellA6=row6.createCell(1);
        cellA6.setCellValue((g6.getSelectedItem()).toString());
        
        Row row7=sheet1.createRow(8);
        Cell cell7=row7.createCell(0);
        cell7.setCellValue(com5.getSelectedItem().toString());
        Cell cellA7=row7.createCell(1);
        cellA7.setCellValue((g7.getSelectedItem()).toString());
        
         Row row8=sheet1.createRow(9);
        Cell cell8=row8.createCell(0);
        cell8.setCellValue(com6.getSelectedItem().toString());
        Cell cellA8=row8.createCell(1);
        cellA8.setCellValue((g8.getSelectedItem()).toString());
        
        Row row9=sheet1.createRow(10);
        Cell cell9=row9.createCell(0);
        cell9.setCellValue(com7.getSelectedItem().toString());
        Cell cellA9=row9.createCell(1);
        cellA9.setCellValue((g9.getSelectedItem()).toString());
        
        Row row10=sheet1.createRow(11);
        Cell cell10=row10.createCell(0);
        cell10.setCellValue(com8.getSelectedItem().toString());
        Cell cellA10=row10.createCell(1);
        cellA10.setCellValue((g10.getSelectedItem()).toString());
        
         Row row11=sheet1.createRow(12);
        Cell cell11=row11.createCell(0);
        cell11.setCellValue(com9.getSelectedItem().toString());
        Cell cellA11=row11.createCell(1);
        cellA11.setCellValue((g11.getSelectedItem()).toString());
        
         Row row12=sheet1.createRow(13);
        Cell cell12=row12.createCell(0);
        cell12.setCellValue(com10.getSelectedItem().toString());
        Cell cellA12=row12.createCell(1);
        cellA12.setCellValue((g12.getSelectedItem()).toString());
        
        Row row13=sheet1.createRow(15);
        Cell cell13=row13.createCell(0);
        cell13.setCellValue("Sem 7 GPA Value");
        Cell cellA13=row13.createCell(1);
        cellA13.setCellValue(s1gpa.getText());
        
        
        
        try{
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int result = fc.showSaveDialog(this);
            String path="";
            if(result == JFileChooser.APPROVE_OPTION){
                path=fc.getCurrentDirectory().getAbsolutePath();
            }
            int response=JOptionPane.showConfirmDialog(this,"Your file location: "+path+"\n Confirm saving...","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(response == JOptionPane.YES_OPTION){
                FileOutputStream output = new FileOutputStream(path +"\\"+ "sem7.xls");
                JOptionPane.showMessageDialog(null,"Sem 7 GPA Details saved successfully on " + path);
                workbook.write(output);
                output.close();
            }
            
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn3;
    private javax.swing.JComboBox<String> com1;
    private javax.swing.JComboBox<String> com10;
    private javax.swing.JComboBox<String> com2;
    private javax.swing.JComboBox<String> com3;
    private javax.swing.JComboBox<String> com4;
    private javax.swing.JComboBox<String> com5;
    private javax.swing.JComboBox<String> com6;
    private javax.swing.JComboBox<String> com7;
    private javax.swing.JComboBox<String> com8;
    private javax.swing.JComboBox<String> com9;
    private javax.swing.JComboBox<String> g1;
    private javax.swing.JComboBox<String> g10;
    private javax.swing.JComboBox<String> g11;
    private javax.swing.JComboBox<String> g12;
    private javax.swing.JComboBox<String> g2;
    private javax.swing.JComboBox<String> g3;
    private javax.swing.JComboBox<String> g4;
    private javax.swing.JComboBox<String> g5;
    private javax.swing.JComboBox<String> g6;
    private javax.swing.JComboBox<String> g7;
    private javax.swing.JComboBox<String> g8;
    private javax.swing.JComboBox<String> g9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel s1gpa;
    // End of variables declaration//GEN-END:variables
}
